---
# tasks file for db
- name: Show info about the env this host belongs to tasks file for db
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Change mongo config file
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  notify: restart mongod

